<?php

namespace Database\Seeders;

use App\Models\UserModel;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
        'username' => 'admin',
        'password' => Hash::make('admin123'),
        'nama' => 'Administrator',
        'nip' => '123456789',
        'email' => 'admin@example.com',
        'level_id' => 1,
        'email_verified_at' => now(),
    ],
[
        'username' => 'pimpinan',
        'password' => Hash::make('pimpinan123'),
        'nama' => 'Rosa Andrie Asmara, ST., MT., Dr. Eng.',
        'nip' => '198010102005011001',
        'email' => 'pimpinan@example.com',
        'level_id' => 2,
        'email_verified_at' => now(),
    ],
[
        'username' => 'dosen',
        'password' => Hash::make('dosen123'),
        'nama' => 'Dosen',
        'nip' => '3456789',
        'email' => 'dosen@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'ahmadi',
        'password' => Hash::make('ahmadi123'),
        'nama' => 'Ahmadi Yuli Ananta, ST., M.M.',
        'nip' => '198107052005011002',
        'email' => 'dosen1@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'ariadi',
        'password' => Hash::make('ariadi123'),
        'nama' => 'Ariadi Retno Ririd, S.Kom., M.Kom.',
        'nip' => '198108102005012002',
        'email' => 'dosen2@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'arief',
        'password' => Hash::make('arief123'),
        'nama' => 'Arief Prasetyo, S.Kom., M.Kom.',
        'nip' => '197903132008121002',
        'email' => 'dosen3@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'atiqah',
        'password' => Hash::make('atiqah013'),
        'nama' => 'Atiqah Nurul Asri, S.Pd., M.Pd.',
        'nip' => '197606252005012001',
        'email' => 'dosen4@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'banni',
        'password' => Hash::make('banni123'),
        'nama' => 'Banni Satria Andoko, S. Kom., M.MSI',
        'nip' => '198108092010121002',
        'email' => 'dosen5@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'budi',
        'password' => Hash::make('budi033'),
        'nama' => 'Budi Harijanto, ST., M.MKom.',
        'nip' => '196201051990031002',
        'email' => 'dosen6@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'cahya',
        'password' => Hash::make('cahya013'),
        'nama' => 'Cahya Rahmad, ST., M.Kom., Dr. Eng.',
        'nip' => '197202022005011002',
        'email' => 'dosen7@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'deddy',
        'password' => Hash::make('deddy113'),
        'nama' => 'Deddy Kusbianto PA, Ir., M.Mkom.',
        'nip' => '196211281988111001',
        'email' => 'dosen72@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'dhebys',
        'password' => Hash::make('dhebys043'),
        'nama' => 'Dhebys Suryani, S.Kom., MT',
        'nip' => '198311092014042001',
        'email' => 'dosen8@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'dimas',
        'password' => Hash::make('dimas043'),
        'nama' => 'Dimas Wahyu Wibowo, ST., MT.',
        'nip' => '198410092015041001',
        'email' => 'dosen9@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'dwi',
        'password' => Hash::make('dwi013'),
        'nama' => 'Dwi Puspitasari, S.Kom., M.Kom.',
        'nip' => '197911152005012002',
        'email' => 'dosen10@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'eka',
        'password' => Hash::make('eka043'),
        'nama' => 'Eka Larasati Amalia, S.ST., MT.',
        'nip' => '198807112015042005',
        'email' => 'dosen11@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'ekojono',
        'password' => Hash::make('ekojono033'),
        'nama' => 'Ekojono, ST., M.Kom.',
        'nip' => '195912081985031004',
        'email' => 'dosen12@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'ely',
        'password' => Hash::make('ely123'),
        'nama' => 'Ely Setyo Astuti, ST., MT.',
        'nip' => '197605152009122001',
        'email' => 'dosen13@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'erfan',
        'password' => Hash::make('erfan013'),
        'nama' => 'Erfan Rohadi, ST., M.Eng., Ph.D.',
        'nip' => '197201232008011006',
        'email' => 'dosen14@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'gunawan',
        'password' => Hash::make('gunawan123'),
        'nama' => 'Gunawan Budi Prasetyo, ST., MMT., Ph.D.',
        'nip' => '197704242008121001',
        'email' => 'dosen15@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'hendra',
        'password' => Hash::make('hendra043'),
        'nama' => 'Hendra Pradibta, SE., M.Sc.',
        'nip' => '198305212006041003',
        'email' => 'dosen16@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'imam',
        'password' => Hash::make('imam123'),
        'nama' => 'Imam Fahrur Rozi, ST., MT.',
        'nip' => '198406102008121004',
        'email' => 'dosen17@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'indra',
        'password' => Hash::make('indra013'),
        'nama' => 'Indra Dharma Wijaya, ST., M.MT.',
        'nip' => '197305102008011010',
        'email' => 'dosen18@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'luqman',
        'password' => Hash::make('luqman043'),
        'nama' => 'Luqman Affandi, S.Kom., MMSI',
        'nip' => '198211302014041001',
        'email' => 'dosen19@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'mungki',
        'password' => Hash::make('mungki013'),
        'nama' => 'Mungki Astiningrum, ST., M.Kom.',
        'nip' => '197710302005012001',
        'email' => 'dosen20@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'pramana',
        'password' => Hash::make('pramana043'),
        'nama' => 'Pramana Yoga Saputra, S.Kom., MMT.',
        'nip' => '198805042015041001',
        'email' => 'dosen21@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'putra',
        'password' => Hash::make('putra043'),
        'nama' => 'Putra Prima A., ST., M.Kom.',
        'nip' => '198611032014041001',
        'email' => 'dosen22@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'rawansyah',
        'password' => Hash::make('rawansyah033'),
        'nama' => 'Rawansyah., Drs., M.Pd.',
        'nip' => '195906201994031001',
        'email' => 'dosen23@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'ridwan',
        'password' => Hash::make('ridwan123'),
        'nama' => 'Ridwan Rismanto, SST., M.Kom.',
        'nip' => '198603182012121001',
        'email' => 'dosen24@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'rudy',
        'password' => Hash::make('rudy033'),
        'nama' => 'Rudy Ariyanto, ST., M.Cs.',
        'nip' => '197111101999031002',
        'email' => 'dosen25@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'dr',
        'password' => Hash::make('dr043'),
        'nama' => 'Dr. Shohib Muslim, S.H., M.Hum',
        'nip' => '198507222014041001',
        'email' => 'dosen26@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'ulla',
        'password' => Hash::make('ulla123'),
        'nama' => 'Ulla Delfana Rosiani, ST., MT.',
        'nip' => '197803272003122002',
        'email' => 'dosen27@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'usman',
        'password' => Hash::make('usman043'),
        'nama' => 'Usman Nurhasan, S.Kom., MT.',
        'nip' => '198609232015041001',
        'email' => 'dosen28@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'widaningsih',
        'password' => Hash::make('widaningsih123'),
        'nama' => 'Widaningsih Condrowardhani, SH, MH.',
        'nip' => '198103182010122002',
        'email' => 'dosen29@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'yan',
        'password' => Hash::make('yan013'),
        'nama' => 'Yan Watequlis Syaifuddin, ST., M.MT.',
        'nip' => '198101052005011005',
        'email' => 'dosen30@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'yuri',
        'password' => Hash::make('yuri123'),
        'nama' => 'Yuri Ariyanto, S.Kom., M.Kom.',
        'nip' => '198007162010121002',
        'email' => 'dosen31@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'agung',
        'password' => Hash::make('agung033'),
        'nama' => 'Agung Nugroho Pramudhita, S.T., M.T.',
        'nip' => '198902102019031020',
        'email' => 'dosen32@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'annisa',
        'password' => Hash::make('annisa033'),
        'nama' => 'Annisa Puspa Kirana, S.Kom., M.Kom',
        'nip' => '198901232019032016',
        'email' => 'dosen33@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'annisa',
        'password' => Hash::make('annisa033'),
        'nama' => 'Annisa Taufika Firdausi, ST., MT.',
        'nip' => '198712142019032012',
        'email' => 'dosen34@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'anugrah',
        'password' => Hash::make('anugrah033'),
        'nama' => 'Anugrah Nur Rahmanto, S.Sn., M.Ds.',
        'nip' => '199112302019031016',
        'email' => 'dosen35@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'arie',
        'password' => Hash::make('arie033'),
        'nama' => 'Arie Rachmad Syulistyo, S.Kom., M.Kom',
        'nip' => '198708242019031010',
        'email' => 'dosen36@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'dian',
        'password' => Hash::make('dian033'),
        'nama' => 'Dian Hanifudin Subhi, S.Kom., M.Kom.',
        'nip' => '198806102019031018',
        'email' => 'dosen37@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'dika',
        'password' => Hash::make('dika033'),
        'nama' => 'Dika Rizky Yunianto, S.Kom, M.Kom',
        'nip' => '199206062019031017',
        'email' => 'dosen38@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'elok',
        'password' => Hash::make('elok033'),
        'nama' => 'Elok Nur Hamdana, S.T., M.T',
        'nip' => '198610022019032011',
        'email' => 'dosen39@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'kadek',
        'password' => Hash::make('kadek033'),
        'nama' => 'Kadek Suarjuna Batubulan, S.Kom, MT',
        'nip' => '199003202019031016',
        'email' => 'dosen40@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'meyti',
        'password' => Hash::make('meyti033'),
        'nama' => 'Meyti Eka Apriyani ST., MT.',
        'nip' => '198704242019032017',
        'email' => 'dosen41@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'afif',
        'password' => Hash::make('afif123'),
        'nama' => 'Muhammad Afif Hendrawan.,S.Kom., MT',
        'nip' => '199111282019031013',
        'email' => 'dosen42@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'khairy',
        'password' => Hash::make('khairy123'),
        'nama' => 'Muhammad Shulhan Khairy, S.Kom, M.Kom',
        'nip' => '199205172019031020',
        'email' => 'dosen43@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'mustika',
        'password' => Hash::make('mustika033'),
        'nama' => 'Mustika Mentari, S.Kom., M.Kom',
        'nip' => '198806072019032016',
        'email' => 'dosen44@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'retno',
        'password' => Hash::make('retno033'),
        'nama' => 'Retno Damayanti, S.Pd., M.T.',
        'nip' => '198910042019032023',
        'email' => 'dosen45@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'sofyan',
        'password' => Hash::make('sofyan033'),
        'nama' => 'Sofyan Noor Arief, S.ST., M.Kom.',
        'nip' => '198908132019031017',
        'email' => 'dosen46@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'vipkas',
        'password' => Hash::make('vipkas033'),
        'nama' => 'Vipkas Al Hadid Firdaus, ST,. MT',
        'nip' => '199105052019031029',
        'email' => 'dosen47@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'vivi',
        'password' => Hash::make('vivi033'),
        'nama' => 'Vivi Nur Wijayaningrum, S.Kom, M.Kom',
        'nip' => '199308112019032025',
        'email' => 'dosen48@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'vivin',
        'password' => Hash::make('vivin033'),
        'nama' => 'Vivin Ayu Lestari, S.Pd., M.Kom.',
        'nip' => '199106212019032020',
        'email' => 'dosen49@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'yoppy',
        'password' => Hash::make('yoppy033'),
        'nama' => 'Yoppy Yunhasnawa, S.ST., M.Sc.',
        'nip' => '198906212019031013',
        'email' => 'dosen50@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'bagas',
        'password' => Hash::make('bagas033'),
        'nama' => 'Bagas Satya Dian Nugraha, ST., MT.',
        'nip' => '199006192019031017',
        'email' => 'dosen51@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'candra',
        'password' => Hash::make('candra033'),
        'nama' => 'Candra Bella Vista, S.Kom., MT.',
        'nip' => '199412172019032020',
        'email' => 'dosen52@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'faiz',
        'password' => Hash::make('faiz033'),
        'nama' => 'Faiz Ushbah Mubarok, S.Pd., M.Pd.',
        'nip' => '199305052019031018',
        'email' => 'dosen53@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'habibie',
        'password' => Hash::make('habibie033'),
        'nama' => 'Habibie Ed Dien, S.Kom., M.T.',
        'nip' => '199204122019031013',
        'email' => 'dosen54@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'ika',
        'password' => Hash::make('ika033'),
        'nama' => 'Ika Kusumaning Putri, S.Kom., MT.',
        'nip' => '199110142019032020',
        'email' => 'dosen55@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'irsyad',
        'password' => Hash::make('irsyad033'),
        'nama' => 'Irsyad Arif Mashudi, S.Kom., M.Kom',
        'nip' => '198902012019031009',
        'email' => 'dosen56@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'mamluatul',
        'password' => Hash::make('mamluatul033'),
        'nama' => 'Mamluatul Haniah, S.Kom., M.Kom',
        'nip' => '199002062019032013',
        'email' => 'dosen57@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'milyun',
        'password' => Hash::make('milyun033'),
        'nama' => 'Milyun Nima Shoumi, S.Kom., M.Kom',
        'nip' => '198805072019032012',
        'email' => 'dosen58@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'moch',
        'password' => Hash::make('moch033'),
        'nama' => 'Moch. Zawaruddin Abdullah, S.ST., M.Kom',
        'nip' => '198902102019031019',
        'email' => 'dosen59@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'noprianto',
        'password' => Hash::make('noprianto033'),
        'nama' => 'Noprianto, S.Kom., M.Eng',
        'nip' => '198911082019031020',
        'email' => 'dosen60@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'rokhimatul',
        'password' => Hash::make('rokhimatul033'),
        'nama' => 'Rokhimatul Wakhidah, S.Pd., M.T.',
        'nip' => '198903192019032013',
        'email' => 'dosen61@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'septian',
        'password' => Hash::make('septian033'),
        'nama' => 'Septian Enggar Sukmana, S.Pd., M.T',
        'nip' => '198909012019031010',
        'email' => 'dosen62@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'wilda',
        'password' => Hash::make('wilda033'),
        'nama' => 'Wilda Imama Sabilla, S.Kom., M.Kom',
        'nip' => '199208292019032023',
        'email' => 'dosen63@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'ade',
        'password' => Hash::make('ade033'),
        'nama' => 'Ade Ismail, S.Kom., M.TI',
        'nip' => '199107042019031021',
        'email' => 'dosen64@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'rakhmat',
        'password' => Hash::make('rakhmat033'),
        'nama' => 'Rakhmat Arianto, S.ST., M.Kom',
        'nip' => '198701082019031004',
        'email' => 'dosen65@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'm',
        'password' => Hash::make('m033'),
        'nama' => 'M. Hasyim Ratsanjani, S.Kom., M.Kom',
        'nip' => '199003052019031013',
        'email' => 'dosen66@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'farid',
        'password' => Hash::make('farid123'),
        'nama' => 'Farid Angga Pribadi, S.Kom.,M.Kom',
        'nip' => '198910072020121003',
        'email' => 'dosen67@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'vit',
        'password' => Hash::make('vit123'),
        'nama' => 'Vit Zuraida,S.Kom., M.Kom.',
        'nip' => '198901092020122005',
        'email' => 'dosen68@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'astrifidha',
        'password' => Hash::make('astrifidha033'),
        'nama' => 'Astrifidha Rahma Amalia,S.Pd., M.Pd.',
        'nip' => '199405212022032006',
        'email' => 'dosen69@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'endah',
        'password' => Hash::make('endah033'),
        'nama' => 'Endah Septa Sintiya,S.Pd., M.Kom',
        'nip' => '199401312022032007',
        'email' => 'dosen70@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ],
[
        'username' => 'toga',
        'password' => Hash::make('toga033'),
        'nama' => 'Toga Aldila Cinderatama,S.ST., M.Sc.',
        'nip' => '198710112022031002',
        'email' => 'dosen71@example.com',
        'level_id' => 3,
        'email_verified_at' => now(),
    ]
        ];

        foreach ($users as $user) {
            if (!UserModel::where('username', $user['username'])->exists()) {
                UserModel::create($user);
            }
        }
    }
}